using SportForAlle.Api.Helpers;

namespace SportForAlle.Api.Models;

/// <summary>
/// Shared identity and audit trail: a client-generated <see cref="Id"/>, plus
/// when an entity was created and changed, and by whom.
/// </summary>
/// <remarks>
/// Ids are Guids generated by the entity itself (<see cref="Guid.NewGuid"/>) at
/// construction, not by the database. That means an entity has a real,
/// stable identity from the moment it exists in memory - useful because
/// several entities in this model (<see cref="Borrower"/> creating a
/// <see cref="Ban"/>, for example) reference their own id while building
/// related records, before anything is saved.
///
/// <see cref="CreatedByStaffId"/> and <see cref="UpdatedByStaffId"/> are
/// nullable because they cannot be guaranteed for every mutation in the
/// system, not because nothing populates them - the core CRUD services
/// (Borrower, Guardian, Equipment, EquipmentCategory, Loan) resolve the
/// calling Staff member from the bearer token via
/// <c>Helpers/CurrentUserContext.cs</c> and pass it into <see cref="Touch"/>
/// and into each constructor, see docs/adr/0019-staff-auth0-mapping.md.
/// Whatever hasn't been built yet (Note, Ban, ContactAttempt) still passes
/// null until it is. The columns were added ahead of that stage so it did
/// not need its own migration.
///
/// There is deliberately no <c>DeletedAt</c>/<c>DeletedByStaffId</c> here.
/// Deletion of personal data (borrowers, guardians) needs an anonymisation
/// policy that has not been decided yet, see docs/09-lover-og-regler.md - a
/// soft-delete flag would be built ahead of that decision.
/// </remarks>
public abstract class AuditableEntity
{
    protected AuditableEntity(IClock clock, Guid? createdByStaffId)
    {
        Id = Guid.NewGuid();
        CreatedAt = clock.UtcNow;
        CreatedByStaffId = createdByStaffId;
    }

    /// <summary>Required by EF Core, which materialises entities without a public constructor.</summary>
    protected AuditableEntity()
    {
    }

    public Guid Id { get; private set; }

    public DateTimeOffset CreatedAt { get; private set; }

    public Guid? CreatedByStaffId { get; private set; }

    public DateTimeOffset? UpdatedAt { get; private set; }

    public Guid? UpdatedByStaffId { get; private set; }

    /// <summary>Records that a mutation happened. Called by every state-changing method on a subclass.</summary>
    protected void Touch(IClock clock, Guid? staffId)
    {
        UpdatedAt = clock.UtcNow;
        UpdatedByStaffId = staffId;
    }
}
