// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportForAlle.Api.Data;

#nullable disable

namespace SportForAlle.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903072434_AddCoreDomainEntities")]
    partial class AddCoreDomainEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportForAlle.Api.Models.Ban", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BorrowerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FeePaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LiftedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LiftedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByStaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId")
                        .IsUnique()
                        .HasFilter("\"LiftedAt\" IS NULL");

                    b.HasIndex("CreatedByStaffId");

                    b.HasIndex("LiftedByStaffId");

                    b.HasIndex("UpdatedByStaffId");

                    b.ToTable("Bans", (string)null);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Borrower", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid>("GuardianId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUnreliable")
                        .HasColumnType("boolean");

                    b.Property<int>("LateReturnCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByStaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByStaffId");

                    b.HasIndex("GuardianId");

                    b.HasIndex("UpdatedByStaffId");

                    b.ToTable("Borrowers", (string)null);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.ContactAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByStaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByStaffId");

                    b.HasIndex("LoanId");

                    b.HasIndex("UpdatedByStaffId");

                    b.ToTable("ContactAttempts", (string)null);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByStaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByStaffId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("UpdatedByStaffId");

                    b.ToTable("Equipment", (string)null);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.EquipmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByStaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByStaffId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedByStaffId");

                    b.ToTable("EquipmentCategories", (string)null);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Guardian", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByStaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByStaffId");

                    b.HasIndex("UpdatedByStaffId");

                    b.ToTable("Guardians", (string)null);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BorrowerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DaysLate")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByStaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByStaffId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("UpdatedByStaffId");

                    b.HasIndex("BorrowerId", "Status");

                    b.HasIndex("Status", "DueDate");

                    b.ToTable("Loans", (string)null);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BorrowerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByStaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("CreatedByStaffId");

                    b.HasIndex("UpdatedByStaffId");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Auth0UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByStaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Auth0UserId")
                        .IsUnique();

                    b.HasIndex("CreatedByStaffId");

                    b.HasIndex("UpdatedByStaffId");

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Ban", b =>
                {
                    b.HasOne("SportForAlle.Api.Models.Borrower", null)
                        .WithMany("Bans")
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("LiftedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Borrower", b =>
                {
                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportForAlle.Api.Models.Guardian", null)
                        .WithMany("Borrowers")
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.ContactAttempt", b =>
                {
                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportForAlle.Api.Models.Loan", null)
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Equipment", b =>
                {
                    b.HasOne("SportForAlle.Api.Models.EquipmentCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.EquipmentCategory", b =>
                {
                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Guardian", b =>
                {
                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Loan", b =>
                {
                    b.HasOne("SportForAlle.Api.Models.Borrower", null)
                        .WithMany()
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportForAlle.Api.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Note", b =>
                {
                    b.HasOne("SportForAlle.Api.Models.Borrower", null)
                        .WithMany()
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Staff", b =>
                {
                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("CreatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportForAlle.Api.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Borrower", b =>
                {
                    b.Navigation("Bans");
                });

            modelBuilder.Entity("SportForAlle.Api.Models.Guardian", b =>
                {
                    b.Navigation("Borrowers");
                });
#pragma warning restore 612, 618
        }
    }
}
