using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SportForAlle.Api.Models;

namespace SportForAlle.Api.Data.Configurations;

/// <summary>
/// Shared key and audit-column setup for every entity inheriting
/// <see cref="AuditableEntity"/>, so each configuration only states what is
/// specific to it.
/// </summary>
internal static class AuditableEntityConfigurationExtensions
{
    public static void ConfigureAuditableEntity<TEntity>(this EntityTypeBuilder<TEntity> builder)
        where TEntity : AuditableEntity
    {
        builder.HasKey(entity => entity.Id);

        // Ids are Guids generated by the entity itself (see AuditableEntity),
        // not by the database - EF Core must not try to generate its own.
        builder.Property(entity => entity.Id).ValueGeneratedNever();

        builder.Property(entity => entity.CreatedAt).IsRequired();

        // Staff attribution is nullable until authentication resolves a real
        // staff id per request - see the remarks on AuditableEntity. SetNull
        // rather than Restrict, so removing a former employee's Staff row
        // does not block deleting it.
        builder.HasOne<Staff>()
            .WithMany()
            .HasForeignKey(entity => entity.CreatedByStaffId)
            .OnDelete(DeleteBehavior.SetNull);

        builder.HasOne<Staff>()
            .WithMany()
            .HasForeignKey(entity => entity.UpdatedByStaffId)
            .OnDelete(DeleteBehavior.SetNull);
    }
}
